name: Pre-release

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Install dependencies
        run: npm ci

      - name: Get next version from changesets
        id: changesets
        run: node getNextVersion.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release branch
        run: |
          VERSION=${{ steps.changesets.outputs.new_version }}
          BRANCH_NAME="release/$VERSION"
          
          git switch -c $BRANCH_NAME
          git push -u origin HEAD
          
          echo "Branch $BRANCH_NAME created and pushed to GitHub."
          echo "Use the tag $VERSION to create the next release in GitHub."

      - name: Bump version
        run: npm run changeset:version

      - name: Commit version bump
        run: |
          git add -A
          git commit -m "Automated-action: version packages updated for ${{ steps.changesets.outputs.new_version }}"
          git push -u origin HEAD

      - name: Create Release Draft
        uses: actions/github-script@v7
        with:
          script: |
            const releaseName = `${{ steps.changesets.outputs.new_version }}`;
            
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: releaseName,
              target_commitish: `release/${releaseName}`,
              name: `Release ${releaseName}`,
              body: `## Changes in this Release\n\n${{ steps.changesets.outputs.changeset_output }}`,
              draft: true
            });