name: Pre-release

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Install dependencies
        run: npm ci

      - name: Get next version from changesets
        id: changesets
        run: |
          CHANGESET_OUTPUT=$(npx changeset status --verbose)
          
          # Verificar si hay cambios en patch, minor o major
          if ! echo "$CHANGESET_OUTPUT" | grep -q "Packages to be bumped at"; then
            echo "No pending changesets to generate a new version"
            exit 1
          fi
          
          HIGHEST_VERSION=$(echo "$CHANGESET_OUTPUT" | grep -o "[0-9]\+\.[0-9]\+\.[0-9]\+" | sort -V | tail -n1)
          
          if [ -z "$HIGHEST_VERSION" ]; then
            echo "Could not determine the version"
            exit 1
          fi
          
          echo "Highest version proposed by changesets: $HIGHEST_VERSION"
          echo "new_version=$HIGHEST_VERSION" >> $GITHUB_OUTPUT
          
          echo "Summary of changes:"
          echo "$CHANGESET_OUTPUT"

      - name: Create release branch
        run: |
          VERSION=${{ steps.changesets.outputs.new_version }}
          BRANCH_NAME="release/v$VERSION"
          
          git switch -c $BRANCH_NAME
          git push -u origin HEAD
          
          echo "Branch $BRANCH_NAME created and pushed to GitHub."
          echo "Use the tag v$VERSION to create the next release in GitHub."

      - name: Bump version
        run: npm run version

      - name: Commit version bump
        run: |
          git add -A
          git commit -m "chore: version packages updated for v${{ steps.changesets.outputs.new_version }}"
          git push -u origin HEAD

      - name: Create Release Draft
        uses: actions/github-script@v7
        with:
          script: |
            const releaseName = `v${{ steps.changesets.outputs.new_version }}`;
            
            await github.rest.repos.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: releaseName,
              target_commitish: `release/${releaseName}`,
              name: `Release ${releaseName}`,
              body: `## Changes in this Release\n\n$(npx changeset status --verbose)\n\n## Next Steps\n1. Review the changes\n2. Publish the release\n3. The release workflow will handle publishing`,
              draft: true
            });