name: Release

on:
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@github.com"

      - name: Switch to release branch
        id: branch
        run: |
          BRANCH_NAME="release/${{ github.event.release.tag_name }}"
          echo "branch_name=$BRANCH_NAME" >> $GITHUB_OUTPUT
          git switch $BRANCH_NAME

      - name: Build packages
        run: npm run build
        
      - name: Publish to CodeArtifact
        run: |
          echo "Simulating publishing to CodeArtifact..."

      - name: Merge release branch to main
        run: |
          git checkout main
          git merge --no-ff ${{ steps.branch.outputs.branch_name }} -m "Automated-action: merge ${{ steps.branch.outputs.branch_name }} into main"
          git push -u origin main

      - name: Delete release branch
        run: |
          git push origin --delete ${{ steps.branch.outputs.branch_name }}
          echo "Deleted release branch ${{ steps.branch.outputs.branch_name }}"
